repos:
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v2.3.0
#     hooks:
#     -   id: check-yaml
#     -   id: end-of-file-fixer
#     -   id: trailing-whitespace
-   repo: https://github.com/KevinChris7/testing-repo
    rev: cf80edb
    hooks:
    -   id: trailing-whitespace
        additional_dependencies: ['--trusted-host' ,'pypi.org' ,'--trusted-host' ,'files.pythonhosted.org']
default_language_version:
    python: python3.7
